const lista = [
    { musculo:"biceps", ejercicio:"Banco scott" }, 
    {   musculo:"biceps", ejercicio:"Sentado alternando mancuernas"},
    {   musculo:"biceps", ejercicio:"Parado con la barra normal"},
    {   musculo:"biceps", ejercicio:"Martillo con mancuernas"},
    {   musculo:"triceps", ejercicio:"Patada de burro"},
    {   musculo:"triceps", ejercicio:"Maquina y la soga"},
    {   musculo:"triceps", ejercicio:"Maquina y la T"},
    {   musculo:"triceps", ejercicio:"empuje"},
    {   musculo:"pecho", ejercicio:"banco plano"},
    {   musculo:"pecho", ejercicio:"banco cabeza en el suelo"},
    {   musculo:"pecho", ejercicio:"maquina"},
    {   musculo:"pecho", ejercicio:"banco inclinado"},
    {   musculo:"pecho", ejercicio:"maquina inclinada con marcuernas"},
    {   musculo:"pecho", ejercicio:"parado levantando las mancuernas y mi mano en el pecho"},
    {   musculo:"hombro", ejercicio:"press militar"},
    {   musculo:"hombro", ejercicio:"levantando mancuernas alternado de frente"},
    {   musculo:"hombro", ejercicio:"levantando mancuernas a los costado y agachado tu cabeza"},
    {   musculo:"hombro", ejercicio:"levantando con barra de frente"},
    {   musculo:"hombro", ejercicio:"sosteniendo de una mano y levantanto "},
    {   musculo:"espalda", ejercicio:"polea alta con agarre cerrado"},
    {   musculo:"espalda", ejercicio:"polea alta con agarre abiero"},
    {   musculo:"espalda", ejercicio:"maquina"},
    {   musculo:"espalda", ejercicio:"olimpica"},
    {   musculo:"pierna", ejercicio:"maquina pantorrilla"},
    {   musculo:"pierna", ejercicio:"camilla acostado"},
    {   musculo:"pierna", ejercicio:"sentadillas"},
    {   musculo:"pierna", ejercicio:"peso muerto"},
    {   musculo:"pierna", ejercicio:"prensa"},
    {   musculo:"abdomen", ejercicio:"rueda"},
    {   musculo:"abdomen", ejercicio:"maquina levantando las piernas"},
]
export { lista };